# Test goal: build with hipSYCL (ROCm backend) to check SYCL code compatibility
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: Clang
#   GPU: hipSYCL
#   Scope: configure, build
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithAssert
#   Compiler: Clang 14
#   MPI: CUDA-aware MPICH (NVIDIA build); threadMPI (AMD build)
#   SIMD: AVX2_256

gromacs:hipsycl-rocm:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-sycl
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-14-cuda-11.4.3-hipsycl-c828db0-rocm-5.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_GPU_OPTIONS: "-DGMX_GPU=SYCL -DGMX_SYCL_HIPSYCL=ON -DHIPSYCL_TARGETS='hip:gfx900'"
    # Unset COMPILER_LAUNCHER (previously set to ccache) because it conflicts with hipSYCL's syclcc-launcher
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_C_COMPILER_LAUNCHER= -DCMAKE_CXX_COMPILER_LAUNCHER="
    COMPILER_MAJOR_VERSION: 14

gromacs:hipsycl-rocm:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .before_script:default
    # Not using ccache because it plays poorly with syclcc-launcher
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-14-cuda-11.4.3-hipsycl-c828db0-rocm-5.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-rocm:configure

gromacs:hipsycl-nvidia:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-sycl
    - .use-mpi
    - .rules:nightly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-14-cuda-11.4.3-hipsycl-c828db0-rocm-5.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_GPU_OPTIONS: "-DGMX_GPU=SYCL -DGMX_SYCL_HIPSYCL=ON -DHIPSYCL_TARGETS='cuda:sm_50,sm_52,sm_60,sm_61,sm_70,sm_75'"
    # Unset COMPILER_LAUNCHER (previously set to ccache) because it conflicts with hipSYCL's syclcc-launcher
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_C_COMPILER_LAUNCHER= -DCMAKE_CXX_COMPILER_LAUNCHER="
    COMPILER_MAJOR_VERSION: 14

gromacs:hipsycl-nvidia:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .before_script:default
    # Not using ccache because it plays poorly with syclcc-launcher
    - .rules:nightly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-14-cuda-11.4.3-hipsycl-c828db0-rocm-5.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-nvidia:configure

gromacs:hipsycl-nvidia:test-gpucommupd-MPI:
  extends:
    - .gromacs:base:test
    - .rules:nightly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-14-cuda-11.4.3-hipsycl-c828db0-rocm-5.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_FORCE_UPDATE_DEFAULT_GPU: 1
    GMX_FORCE_GPU_AWARE_MPI: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-nvidia:build

gromacs:hipsycl-nvidia:regressiontest-gpucommupd-MPI:
  # Test parallelism np/ntomp: 2/2
  # Test parallelism GPU: direct communications, update
  extends:
    - .gromacs:base:regressiontest
    - .rules:nightly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-14-cuda-11.4.3-hipsycl-c828db0-rocm-5.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 2
    REGRESSIONTEST_PARALLEL: "-np"
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_FORCE_UPDATE_DEFAULT_GPU: 1
    GMX_FORCE_GPU_AWARE_MPI: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-nvidia:build
    - job: regressiontests:prepare
  artifacts:
    paths:
      - regressiontests
    when: always
    expire_in: 1 week

