# Test goal: Clang UndefinedBehaviorSanitizer build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: Clang
#   Build type: UBSAN
#   GPU: no
#   Scope: configure, build, unit tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Compiler: Clang 16
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2

gromacs:clang-UBSAN:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-16-tsan
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    COMPILER_MAJOR_VERSION: 16
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=UBSAN"

gromacs:clang-UBSAN:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .use-clang:base
    - .use-ccache
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-16-tsan
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-UBSAN:configure

gromacs:clang-UBSAN:test:
  extends:
    - .gromacs:base:test
    - .use-clang:base
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-16-tsan
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-UBSAN:build

