# Test goal: Continuous integration testing for gmxapi clients development branch.
# Test intents:
#   OS: Ubuntu oldest supported
#   GPU: unspecified
#   GROMACS: main
#   gmxapi: as per GROMACS main
#   client code:
#    * sample_restraint as bundled with GROMACS main
#    * TAF extension example as bundled with GROMACS main
#   Scope: build, install, test
# Test implementation choices (free to change as needed):
#   GROMACS branch: main
#   gmxapi Python package: 0.3 alpha from GROMACS main
#   compiler: clang-9

.sample_taf:
  extends:
    - .variables:default
  stage: test
  variables:
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_MEMORY_LIMIT: 1Gi
    KUBERNETES_MEMORY_REQUEST: 1Gi
  script:
    - export GROMACS_DIR=$PWD/$INSTALL_DIR
    - export GMX_SUFFIX
    - export CMAKE
    - export GMX_DOUBLE
    - bash -x admin/ci-scripts/build-taf-template.sh

sample_taf:openmpi-double:
  extends:
    - .sample_taf
    - .rules:merge-requests
  image: ${CI_REGISTRY_IMAGE}/ci-ubuntu-20.04-llvm-13
  variables:
    CMAKE: "/usr/local/cmake-3.16.3/bin/cmake"
    GMX_SUFFIX: "_mpi_d"
    GMX_DOUBLE: "ON"
  needs:
    - job: gromacs:clang-13-mpi:build

sample_taf:tmpi:
  extends:
    - .sample_taf
    - .rules:merge-requests
  image: ${CI_REGISTRY_IMAGE}/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
  needs:
    - job: gromacs:clang-9:build

.sample_restraint:
  extends:
    - .variables:default
  stage: test
  variables:
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    PLUGIN_TEST_XML: $CI_PROJECT_DIR/py-JUnitTestResults.xml
    PLUGIN_MPI_TEST_XML: $CI_PROJECT_DIR/py-mpi-JUnitTestResults.xml
  script:
    - source $INSTALL_DIR/bin/GMXRC
    - source $VENVPATH/bin/activate
    - GROMACS_ROOT=$PWD/$INSTALL_DIR OMP_NUM_THREADS=1 bash admin/ci-scripts/build-and-test-sample_restraint.sh
  artifacts:
    reports:
      junit:
        - $PLUGIN_TEST_XML
        - $PLUGIN_MPI_TEST_XML
    when: always
    expire_in: 1 week

sample_restraint:clang-9:py-3.7:
  extends:
    - .sample_restraint
    - .use-clang:base
    - .rules:merge-requests
  image: ${CI_REGISTRY_IMAGE}/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  variables:
    VENVPATH: "/root/venv/py3.7"
  needs:
    - job: gromacs:clang-9:build
      artifacts: true

sample_restraint:clang-9:py-3.10:
  extends:
    - .sample_restraint
    - .use-clang:base
    - .rules:merge-requests
  image: ${CI_REGISTRY_IMAGE}/ci-ubuntu-20.04-llvm-9-cuda-11.0.3
  variables:
    VENVPATH: "/root/venv/py3.10"
  needs:
    - job: gromacs:clang-9:build
      artifacts: true
