gitlab-triage:
  extends:
    - .rules:nightly-not-for-release
  image: ruby:2.7
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token $API_TOKEN --source projects --source-id $CI_PROJECT_PATH


