# Mix-in job definitions.

# Centralized definitions of common job parameter values.

.variables:default:
  variables:
    KUBERNETES_CPU_LIMIT: 8
    KUBERNETES_CPU_REQUEST: 4
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_EXTENDED_RESOURCE_NAME: ""
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 0
    CACHE_FALLBACK_KEY: "$CI_JOB_NAME-$CI_JOB_STAGE-master"
    BUILD_DIR: build
    INSTALL_DIR: install
    CMAKE_GMXAPI_OPTIONS: "-DGMX_PYTHON_PACKAGE=ON"
    EXTRA_INSTALLS: "python3-dev python3-setuptools python3-pip python3-pytest"
# TODO: Get these from updated Docker images.

# Our generic before_script to install dependencies and prepare the ccache directory.
.before_script:default:
  before_script:
    - echo $EXTRA_INSTALLS
    - time apt-get -qq update
    - time apt-get -qqy --no-install-suggests --no-install-recommends install
      $EXTRA_INSTALLS
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache

# Jobs that run for merge requests and schedules, but not when GROMACS_RELEASE
# is set. Includes non-gromacs projects. Note that jobs using this rule are
# eligible to run on non-gromacs project infrastructure, and should therefore
# override the default *tag* parameter to exclude tags specific to the GROMACS
# GitLab Runner infrastructure. I.e. in the job definition, set `tags: []`
.rules:basic:
  rules:
    - if: '$GROMACS_RELEASE'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

# Jobs that run for merge requests and schedules, but not when GROMACS_RELEASE
# is set. Excludes non-gromacs projects.
.rules:not-for-release:
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    - if: '$GROMACS_RELEASE'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

# Rule to run a job only in nightly release-preparation pipelines.
# Checks if the GROMACS_RELEASE variable was set (typically through the GitLab web interface).
# Excludes merge_requests and non-gromacs projects.
# TODO: Update to *rules* syntax.
.rules:nightly-only-for-release:
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    - if: '$GROMACS_RELEASE && $CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$GROMACS_RELEASE && $CI_PIPELINE_SOURCE == "schedule"'
      when: always

# Jobs that run on schedules, but not for merge requests or when GROMACS_RELEASE
# is set. Excludes non-gromacs projects.
.rules:nightly-not-for-release:
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    - if: '$GROMACS_RELEASE'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always

# Behavioral templates

# Use a persistent compiler cache to speed up rebuilds for a single job.
.use-ccache:
  cache:
    key: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - ccache/

# Tool chains

.use-cuda:
  variables:
    CMAKE_PRECISION_OPTIONS: "-DGMX_DOUBLE=OFF"
    CUDA_BASE_VERSION: ""
    BUILD_DIR: build-cuda
    CMAKE_EXTRA_OPTIONS: -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/
    CMAKE_GPU_OPTIONS: -DGMX_GPU=ON

# Base definition, not to be used directly.
# Use version-specific `.use-gccX` definitions when defining jobs.
.use-gcc:base:
  variables:
    BUILD_DIR: build-gcc
    CMAKE_COMPILER_SCRIPT: -DCMAKE_C_COMPILER=gcc-$COMPILER_MAJOR_VERSION -DCMAKE_CXX_COMPILER=g++-$COMPILER_MAJOR_VERSION
  before_script:
    - echo $EXTRA_INSTALLS
    - time apt-get -qq update
    - time apt-get -qqy --no-install-suggests --no-install-recommends install
      $EXTRA_INSTALLS
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache

.use-gcc7:
  image: gromacs/ci-gcc-7:master
  variables:
    COMPILER_MAJOR_VERSION: 7
  extends:
    - .use-gcc:base

.use-gcc8:
  image: gromacs/ci-gcc-8:master
  variables:
    COMPILER_MAJOR_VERSION: 8
  extends:
    - .use-gcc:base

.use-gcc8:cuda-10.2:
  image: gromacs/ci-gcc-8-cuda-10.2:master
  variables:
    CUDA_BASE_VERSION: "10.2"
    COMPILER_MAJOR_VERSION: 8

# Base definition, not to be used directly.
# Use version-specific `.use-clangX` definitions when defining jobs.
.use-clang:base:
  variables:
    DEBIAN_FRONTEND: noninteractive
    BUILD_DIR: build-clang
    CMAKE_COMPILER_SCRIPT: -DCMAKE_C_COMPILER=clang-$COMPILER_MAJOR_VERSION -DCMAKE_CXX_COMPILER=clang++-$COMPILER_MAJOR_VERSION
  before_script:
    - echo $EXTRA_INSTALLS
    - time apt-get -qq update
    - time apt-get -qqy --no-install-suggests --no-install-recommends install
      $EXTRA_INSTALLS
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache

.use-clang6:
  image: gromacs/ci-clang-6:master
  variables:
    COMPILER_MAJOR_VERSION: 6
  extends:
    - .use-clang:base

.use-clang7:
  image: gromacs/ci-clang-7:master
  variables:
    COMPILER_MAJOR_VERSION: 7
  extends:
    - .use-clang:base

.use-clang8:
  image: gromacs/cmake-3.15.7-llvm-8-intelopencl-openmpi:2020
  variables:
    COMPILER_MAJOR_VERSION: 8
  extends:
    - .use-clang:base
