#
# Pseudo-jobs to check other pipeline's status
#

gromacs:ci:check-push-pipeline:
  extends:
    - .rules:merge-requests
  stage: wait-for-others
  image: gromacs/ci-docs-llvm-master  # Most lightweight?
  script:
    - python3 admin/ci-scripts/check_gitlab_pipeline.py --token ${GMX_CI_GITLAB_API_KEY} --sha ${CI_COMMIT_SHA}
