# Test for API regression or unexpected breakage.

# Base job definition for sample_restraint tests against GROMACS 2020.
.sample_restraint:clang-8:gmx2020:
  extends:
    - .variables:default
    - .use-clang8
  stage: test
  variables:
    PLUGIN_TEST_XML: $CI_PROJECT_DIR/py-JUnitTestResults.xml
    PLUGIN_MPI_TEST_XML: $CI_PROJECT_DIR/py-mpi-JUnitTestResults.xml
    EXTRA_INSTALLS: "curl libbz2-dev libffi-dev liblzma-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev llvm python-openssl tk-dev zlib1g-dev"
  script:
    - source $INSTALL_DIR/bin/GMXRC
    - source $VENVPATH/bin/activate && INSTALL_DIR=$PWD/$INSTALL_DIR bash -x admin/ci-scripts/build-and-test-sample_restraint-2020.sh
  artifacts:
    reports:
      junit:
        - $PLUGIN_TEST_XML
        - $PLUGIN_MPI_TEST_XML
    when: always
    expire_in: 1 week
  needs:
    - project: gromacs/gromacs
      job: gromacs:clang-8:build
      ref: release-2020
      artifacts: true

sample_restraint:clang-8:gmx2020:3.5.9:
  extends:
    - .sample_restraint:clang-8:gmx2020
  # Run only for changes affecting the python_packaging subdirectory of the release-2020 branch.
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    # Allow explicit trigger through web interface.
    - if: '$GMX_GMXAPI_0_2'
      when: always
    - if: '$GROMACS_RELEASE'
      when: never
    # Run this job only for release-2020 branch and merge-requests targeting it.
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "release-2020" && $CI_COMMIT_BRANCH != "release-2020"'
      when: never
    # GROMACS 2020 API is final, so only test on schedules or when merge requests update the python_packaging sources.
    - changes:
        - python_packaging
      when: always
  variables:
    VENVPATH: "/root/venv/py3.5"
    PY_VER: "3.5.9"

sample_restraint:clang-8:gmx2020:py-3.6.10:
  extends:
    - .sample_restraint:clang-8:gmx2020
  # Run only for changes affecting the python_packaging subdirectory of the release-2020 branch.
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    # Allow explicit trigger through web interface.
    - if: '$GMX_GMXAPI_0_2'
      when: always
    - if: '$GROMACS_RELEASE'
      when: never
    # Run this job only for release-2020 branch and merge-requests targeting it.
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "release-2020" && $CI_COMMIT_BRANCH != "release-2020"'
      when: never
    # GROMACS 2020 API is final, so only test on schedules or when merge requests update the python_packaging sources.
    - changes:
        - python_packaging
      when: always
  variables:
    VENVPATH: "/root/venv/py3.6"
    PY_VER: "3.6.10"

sample_restraint:clang-8:gmx2020:py-3.7.7:
  extends:
    - .sample_restraint:clang-8:gmx2020
  # Run only for changes affecting the python_packaging subdirectory of the release-2020 branch.
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    # Allow explicit trigger through web interface.
    - if: '$GMX_GMXAPI_0_2'
      when: always
    - if: '$GROMACS_RELEASE'
      when: never
    # Run this job only for release-2020 branch and merge-requests targeting it.
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "release-2020" && $CI_COMMIT_BRANCH != "release-2020"'
      when: never
    # GROMACS 2020 API is final, so only test on schedules or when merge requests update the python_packaging sources.
    - changes:
        - python_packaging
      when: always
  variables:
    VENVPATH: "/root/venv/py3.7"
    PY_VER: "3.7.7"

sample_restraint:clang-8:gmx2020:py-3.8.2:
  extends:
    - .sample_restraint:clang-8:gmx2020
  # Run only for changes affecting the python_packaging subdirectory of the release-2020 branch.
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "gromacs"'
      when: never
    # Allow explicit trigger through web interface.
    - if: '$GMX_GMXAPI_0_2'
      when: always
    - if: '$GROMACS_RELEASE'
      when: never
    # Run this job only for release-2020 branch and merge-requests targeting it.
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "release-2020" && $CI_COMMIT_BRANCH != "release-2020"'
      when: never
    # GROMACS 2020 API is final, so only test on schedules or when merge requests update the python_packaging sources.
    - changes:
      - python_packaging
      when: always
  variables:
    VENVPATH: "/root/venv/py3.8"
    PY_VER: "3.8.2"
